sudo: required
dist: trusty
language: c
compiler:
  - gcc

addons:
  apt:
    update: true

before_script:
  - sudo apt install libusb-1.0-0-dev
  - gcc --version
  - nproc

script:
  - CFLAGS=-Werror make -j2

branches:
  only:
  - master
