language: c

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang

addons:
  apt:
    packages:
    - libusb-1.0-0-dev

before_script:
  - gcc --version

script:
  - CFLAGS=-Werror make -j2

branches:
  only:
  - master
